# -*- coding: utf-8 -*-
"""DAC_Phase4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o4a9LIS35cTZsfDe21bFy9wLvrapk_S7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
covid=pd.read_csv("Covid_19_cases4.csv")
covid

mean = np.mean(covid)
mean

std_dev = np.std(covid)
std_dev

from matplotlib import pyplot as plt
x = mean
y = std_dev
plt.plot(mean,std_dev)
plt.title("Line graph")
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()

total_cases = covid['cases'].sum()
total_deaths = covid['deaths'].sum()
labels = ['cases', 'deaths']
sizes = [total_cases, total_deaths]
colors = ['indigo', 'red']
explode = (0.1, 0)
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.axis('equal')
plt.title('Distribution of COVID-19 Cases and Deaths')
plt.show()

plt.bar(mean, std_dev, color=['blue', 'red'])
plt.xlabel('mean')
plt.ylabel('std_dev')
plt.title('Mean and Standard Deviation')
plt.show()

correlation = covid['cases'].corr(covid['deaths'])
print("Correlation between Cases and Deaths:", correlation)

covid['Cases_Variation'] = covid['cases'].pct_change() * 100
covid['Deaths_Variation'] = covid['deaths'].pct_change() * 100
print(covid[['Cases_Variation', 'Deaths_Variation']])